### ISSUE TITLE
Anyone can snooze anyone's reminders

### ISSUE THREAD

**Issue by Foxite** [Mayerch1/RemindmeBot#10]
I've found that I can snooze the reminders that other users created for themselves.

The fix should probably be to only allow the person who gets the reminder to do this. I haven't read the code yet but I can probably implement this myself. But this repo doesn't have a license document or CLA; would you accept a PR that fixes it?

**Comment by Mayerch1** [comment]
This issue was addressed with [1a0333](https://github.com/Mayerch1/RemindmeBot/commit/51a0333c385007bd36e2793f4768da3dc12e9a39)

Whenever someone tries to snooze a `foreign` reminder, the snoozed reminder will be delivered into the DM of that person.
Only authors can snooze reminders server-sided.

The update was rolled out to the official instance a few minutes ago.
